version: '3'
services:
  smtp-server:
    build: .
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
      - "3000:3000"
    volumes:
      - ./dkim:/usr/src/app/dkim
    environment:
      - NODE_ENV=production
    restart: always
