version: '3.8'
services:
  smtp:
    build: .
    ports:
      - "465:465"
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    environment:
      - DOMAIN=mail.bablast.id
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    environment:
      - DOMAIN=mail.bablast.id
